/**
 * @param {*} userId
 * @returns uuId
 */
// It should be used when the client does not send its own code
module.exports.UuidGenerator = userId => {
    // generate a random value.
    const uuId = "00-0-4-1-000".replace(/[^-]/g, s => (((Math.random() + ~~s) * 0x10000) >> s).toString(16).padStart(4, "0"));
    console.info(`uuId generated by ${userId}: ${uuId}`);
    return uuId;
}